server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  server:
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
